from django.urls import path
from Backend import views
urlpatterns=[
    path('',views.admin_login,name="admin_login"),
    path('loginpage/',views.loginpage,name="loginpage"),
    path('adminlogout/',views.adminlogout,name="adminlogout"),
    path('admin_index/',views.admin_index,name="admin_index"),
    path('view_mechanic/',views.view_mechanic,name="view_mechanic"),
    path('request_status_counts/',views.request_status_counts,name="request_status_counts"),
    path('approve_mech/<int:mid>/',views.approve_mech,name="approve_mech"),
    path('reject_mech/<int:mid>/',views.reject_mech,name="reject_mech"),
    path('view_approved_mech/<type>/',views.view_approved_mech,name="view_approved_mech"),
    path('view_pending_mech/<type>/',views.view_pending_mech,name="view_pending_mech"),
    path('view_rejected_mech/<type>/',views.view_rejected_mech,name="view_rejected_mech"),
    path('view_servicecentre/',views.view_servicecentre,name="view_servicecentre"),
    path('approve_servicecentre/<int:sid>',views.approve_servicecentre,name="approve_servicecentre"),
    path('reject_servicecentre/<int:sid>',views.reject_servicecentre,name="reject_servicecentre"),
    path('view_approved_servicecentre/<type>/',views.view_approved_servicecentre,name="view_approved_servicecentre"),
    path('view_rejected_servicecentre/<type>/',views.view_rejected_servicecentre,name="view_rejected_servicecentre"),
    path('view_pending_servicecentre/<type>/',views.view_pending_servicecentre,name="view_pending_servicecentre"),
    path('view_feedback/',views.view_feedback,name="view_feedback"),
    path('add_category/',views.add_category,name="add_category"),
    path('add_product/',views.add_product,name="add_product"),
    path('save_category/',views.save_category,name="save_category"),
    path('save_product/',views.save_product,name="save_product"),
    path('view_category/',views.view_category,name="view_category"),
    path('view_product/',views.view_product,name="view_product"),
    path('order_status_view/',views.order_status_view,name="order_status_view"),
    path('update_order_status_ajax/',views.update_order_status_ajax,name="update_order_status_ajax"),
    path('edit_cat/<int:cid>/', views.edit_cat, name="edit_cat"),
    path('update_category/<int:cid>/', views.update_category, name="update_category"),
    path('delete_cat/<int:cid>/', views.delete_cat, name="delete_cat"),
    path('edit_product/<int:pid>/', views.edit_product, name="edit_product"),
    path('update_product/<int:pid>/', views.update_product, name="update_product"),
    path('delete_product/<int:pid>/', views.delete_product, name="delete_product"),
]

