# Generated by Django 5.0.6 on 2024-06-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
