# Generated by Django 5.0.6 on 2024-06-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Categorname',
            new_name='Categoryname',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='Image',
        ),
    ]
