# Generated by Django 5.0.6 on 2024-06-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Produtname',
            new_name='Productname',
        ),
    ]
