# Generated by Django 5.0.6 on 2024-06-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0007_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
