# Generated by Django 5.0.6 on 2024-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0008_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="chatmessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("sender_type", models.CharField(max_length=50)),
                ("sender_id", models.IntegerField()),
                ("receiver_type", models.CharField(max_length=50)),
                ("receiver_id", models.IntegerField()),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
