# Generated by Django 5.0.6 on 2024-08-17 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0009_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 17, 20, 8, 37, 148253)
            ),
        ),
    ]
