# Generated by Django 5.0.6 on 2024-08-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0011_alter_chatmessage_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 17, 15, 34, 41, 971765, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
