# Generated by Django 5.0.6 on 2024-08-17 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0012_alter_chatmessage_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 17, 15, 53, 29, 763762, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
