# Generated by Django 5.0.6 on 2024-08-15 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0001_initial"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="chatmessages",
        #     name="is_read",
        # ),
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 15, 22, 53, 37, 264722)
            ),
        ),
        # migrations.AlterField(
        #     model_name="messages",
        #     name="date",
        #     field=models.DateTimeField(
        #         blank=True, default=datetime.datetime(2024, 8, 15, 22, 53, 37, 266847)
        #     ),
        # ),
    ]
