# Generated by Django 5.0.6 on 2024-08-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0004_alter_booking_date_booked_alter_messages_date"),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name="ChatMessages",
        #     new_name="Chatmessage",
        # ),
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 15, 23, 2, 23, 519709)
            ),
        ),
        # migrations.AlterField(
        #     model_name="messages",
        #     name="date",
        #     field=models.DateTimeField(
        #         blank=True, default=datetime.datetime(2024, 8, 15, 23, 2, 23, 522894)
        #     ),
        # ),
    ]
