# Generated by Django 5.0.6 on 2024-08-15 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0006_alter_booking_date_booked_alter_messages_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="messagedb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("sender_type", models.CharField(max_length=50)),
                ("sender_id", models.IntegerField()),
                ("receiver_type", models.CharField(max_length=50)),
                ("receiver_id", models.IntegerField()),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 15, 23, 10, 7, 661606)
            ),
        ),
        # migrations.AlterField(
        #     model_name="messages",
        #     name="date",
        #     field=models.DateTimeField(
        #         blank=True, default=datetime.datetime(2024, 8, 15, 23, 10, 7, 662664)
        #     ),
        # ),
    ]
