# Generated by Django 5.0.6 on 2024-08-15 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0010_alter_booking_date_booked_alter_messages_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="messagedb",
        ),
        # migrations.DeleteModel(
        #     name="Messages",
        # ),
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 15, 23, 28, 24, 264793)
            ),
        ),
    ]
