# Generated by Django 5.0.6 on 2024-08-16 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0013_delete_chatmessage_alter_booking_date_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 16, 10, 33, 31, 893160)
            ),
        ),
    ]
