# Generated by Django 5.0.6 on 2024-08-17 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0015_alter_booking_date_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 17, 20, 8, 37, 157921)
            ),
        ),
    ]
