# Generated by Django 5.0.6 on 2024-08-21 14:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0020_cart_order_order_user_alter_booking_date_booked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="order",
        ),
        migrations.AddField(
            model_name="cart",
            name="order_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="Webapp.order",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 20, 8, 15, 114176)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Webapp.userdatas",
            ),
        ),
    ]
