# Generated by Django 5.0.6 on 2024-08-22 15:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0022_order_status_alter_booking_date_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 22, 21, 0, 35, 420619)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="Webapp.order",
            ),
        ),
    ]
