# Generated by Django 5.0.6 on 2024-08-22 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0023_alter_booking_date_booked_alter_cart_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="order_id",
        ),
        migrations.AddField(
            model_name="order",
            name="cartid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date_booked",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 22, 21, 13, 0, 648256)
            ),
        ),
    ]
